stages: 
    - build
    - test
cache:
    paths:
        - node_modules/

buildJob:
    stage: build
    script:
        - pip3 install -r requirements.txt
        - cd frontend/ 
        - cnpm install
        - cnpm run build

testJob:
    stage: test
    script:
        - cnpm run unit
        - cd ..
        - ./manage.py test