stages: 
    - build
    - test

buildJob:
    stage: build
    script:
        - pip3 install -r requirements.txt
        - cd frontend/ 
        - cnpm install
        - cnpm run build

testJob:
    stage: test
    script:
        - cd frontend/
        - cnpm install
        - cnpm run unit
        - cd ..
        - mysql -uroot -p
        - ''
        - create database liveplat default character set utf8 collate utf8_unicode_ci;
        - exit;
        - python3 ./manage.py makemigrations
        - python3 ./manage.py migrate
        - python3 ./manage.py test