stages: 
  - build
  - test
cache:
  paths:
    - node_modules/

buildjob:
  stage: build
  script:
    - pip3 install -r requirements.txt
    - cd frontend/ 
    - npm install
    - npm run build
